import { IFullTender, TenderStatus, TenderType, WorkerType, ContractType, RecruitmentReason, VehicleRequired } from './tender';
import { IUser } from "./account";

export const dummyAccount : IUser = {
        is_dummy: true,
        id: 33,
        email: "hiddengard@gmail.com",
        firstname: "Andrei",
        lastname: "Trubinov",
        mobile: "+79223849389",
        landline: "+79223849389",
        is_active: true,
        date_joined: "2021-10-06T08:06:04+00:00",
        is_company: true,
        is_agency: false,
        establishment: {
                id: 2,
                name: "ANDREI TRUBINOV",
                siret: "50763943300014",
                address: {
                streetnumber: "55",
                route: "Chemin du Marais de Lenglet",
                locality: "Aire-sur-la-Lys",
                administrativearealevel2: "Pas-de-Calais",
                administrativearealevel1: "Hauts-de-France",
                country: "FR",
                postalcode: "62120",
                formattedaddress: "55 Chem. du Marais de Lenglet, 62120 Aire-sur-la-Lys, France",
                placeid: "Ejw1NSBDaGVtLiBkdSBNYXJhaXMgZGUgTGVuZ2xldCwgNjIxMjAgQWlyZS1zdXItbGEtTHlzLCBGcmFuY2UiGhIYChQKEgmTO_kYzALdRxEOzeYRehbVnRA3",
                lng: 2.4193453,
                lat: 50.6273972,
                },
        },
        business_sectors: [],
};

export const dummyTenders: IFullTender[] = [
    {
        id: 1,
        created: "2021-11-19T11:33:29.870436+00:00",
        modified: "2021-11-19T11:33:29.969073+00:00",
        status: "PUBLISHED",
        author: {
            id: 33,
            establishment: {
                id: 1,
                name: "MIRONOV PHILIPPE",
                siret: "50763943300014",
                address: {
                    streetnumber: "55",
                    route: "Chemin du Marais de Lenglet",
                    locality: "Aire-sur-la-Lys",
                    administrativearealevel2: "Pas-de-Calais",
                    administrativearealevel1: "Hauts-de-France",
                    country: "FR",
                    postalcode: "62120",
                    formattedaddress:
                        "55 Chem. du Marais de Lenglet, 62120 Aire-sur-la-Lys, France",
                    placeid:
                        "Ejw1NSBDaGVtLiBkdSBNYXJhaXMgZGUgTGVuZ2xldCwgNjIxMjAgQWlyZS1zdXItbGEtTHlzLCBGcmFuY2UiGhIYChQKEgmTO_kYzALdRxEOzeYRehbVnRA3",
                    lng: 2.4193453,
                    lat: 50.6273972,
                },
            },
            business_sectors: [],
        },
        tendertype: "DELEGATION",
        clientref: "marefclient34",
        jobtitle: "Flutter Developer",
        remote: true,
        numberofworkers: 2,
        workertype: "INTERIM",
        contracttype: "TEMPORARY",
        start: "2021-11-03T09:00:00+00:00",
        end: "2021-11-03T18:00:00+00:00",
        hourscount: 9.0,
        grosssalary: 50.0,
        salarycurrency: "EUR",
        recruitmentreason: "ACC_TEMP",
        requireddriverlicense: "B",
        vehiclerequired: "PREFERABLE",
        formation: "BEP Cuisine",
        certification: "CertiPE A",
        software: "emacs, vim, zsh",
        budget: 4500.0,
        budgetcurrency: "EUR",
        payroll: 1,
        additionalpayrollinformation: "",
        firstname: "Gérard",
        lastname: "Dufour",
        phonenumber: "+33479122132",
        contactinformation: "Informations de contact",
        publishdate: "2021-11-01T00:11:19+00:00",
        workplace: {
            streetnumber: "55",
            route: "Chemin du Marais de Lenglet",
            locality: "Paris",
            administrativearealevel2: "Pas-de-Calais",
            administrativearealevel1: "Hauts-de-France",
            country: "FR",
            postalcode: "62120",
            formattedaddress:
                "55 Chem. du Marais de Lenglet, 62120 Aire-sur-la-Lys, France",
            placeid:
                "Ejw1NSBDaGVtLiBkdSBNYXJhaXMgZGUgTGVuZ2xldCwgNjIxMjAgQWlyZS1zdXItbGEtTHlzLCBGcmFuY2UiGhIYChQKEgmTO_kYzALdRxEOzeYRehbVnRA3",
            lng: 2.4193453,
            lat: 50.6273972,
        },
        business_sectors: [
            {
                id: 1,
                code: 27,
                labelfr: "Informatique / Télécommunication",
                labelen: "Information Technologies",
                labelde: "Informatik",
            },
            {
                id: 2,
                code: 30,
                labelfr: "Mobile",
                labelen: "Mobile",
                labelde: "Mobile",
            },
            {
                id: 3,
                code: 23,
                labelfr: "Développement",
                labelen: "Development",
                labelde: "Gastgewerbe / Hotellerie / Tourismus",
            },
            {
                id: 4,
                code: 23,
                labelfr: "Dart",
                labelen: "Dart",
                labelde: "Gastgewerbe / Hotellerie / Tourismus",
            },
        ],
        providedworkers: [],
        periods: [
            {
                id: 1,
                tender: 2,
                start: "2021-11-03T09:00:00+00:00",
                end: "2021-11-03T18:00:00+00:00",
                pause: 30,
            },
        ],
        requiredlanguages: [
            {
                id: 1,
                tender: 2,
                language: "FR",
                spoken: "C1",
                written: "B2",
                notes: "Faut parler la France",
            },
            {
                id: 2,
                tender: 2,
                language: "EN",
                spoken: "C1",
                written: "B2",
                notes: "Where is my umbrella ?",
            },
            {
                id: 3,
                tender: 2,
                language: "DE",
                spoken: "A2",
                written: "A1",
                notes: "",
            },
        ],
        proposals: [
            {
                id: 1,
                created: "2021-11-21T16:33:26.602614+00:00",
                modified: "2021-11-21T16:33:26.602713+00:00",
                status: "PUBLISHED",
                tender: 2,
                author: {
                    id: 5,
                    establishment: {
                        id: 1,
                        name: "Artefact",
                        siret: "50763943300014",
                        address: {
                            streetnumber: "55",
                            route: "Chemin du Marais de Lenglet",
                            locality: "Paris",
                            administrativearealevel2: "Pas-de-Calais",
                            administrativearealevel1: "Hauts-de-France",
                            country: "FR",
                            postalcode: "62120",
                            formattedaddress:
                                "55 Chem. du Marais de Lenglet, 62120 Aire-sur-la-Lys, France",
                            placeid:
                                "Ejw1NSBDaGVtLiBkdSBNYXJhaXMgZGUgTGVuZ2xldCwgNjIxMjAgQWlyZS1zdXItbGEtTHlzLCBGcmFuY2UiGhIYChQKEgmTO_kYzALdRxEOzeYRehbVnRA3",
                            lng: 2.4193453,
                            lat: 50.6273972,
                        },
                    },
                    business_sectors: [
                        {
                            id: 10,
                            code: 10,
                            labelfr: "Banques",
                            labelen: "Banks",
                            labelde: "Banken",
                        },
                        {
                            id: 41,
                            code: 41,
                            labelfr: "Mode",
                            labelen: "Fashion",
                            labelde: "Mode / Fashion",
                        },
                        {
                            id: 38,
                            code: 38,
                            labelfr: "Télécommunications",
                            labelen: "Telecommunications",
                            labelde: "Telekommunikation",
                        },
                    ],
                },
                publishdate: "2021-11-21T16:17:36+00:00",
                message:
                    "Ceci est le message supplémentaire fourni par l'agence.\r\nIl peut être multiligne",
                coefficient0: 1.9,
                coefficient1: 2.5,
                includeterms: true,
                increasedcoefficient0: null,
                increasedcoefficient1: null,
                nbdays: null,
                nbhours: null,
                offer: true,
                otherexpenses0: null,
                otherexpenses1: null,
                prepaidoffer: true,
                rawhourlyrate: null,
                total0: 4000.0,
                total1: 2000.0,
                workers: [
                    {
                        id: 1,
                        created: "2021-11-21T16:28:28.063296+00:00",
                        modified: "2021-11-21T16:28:28.063354+00:00",
                        address: {
                            streetnumber: "27",
                            route: "Allées Forain-François Verdier",
                            locality: "Toulouse",
                            administrativearealevel2: "Haute-Garonne",
                            administrativearealevel1: "Occitanie",
                            country: "FR",
                            postalcode: "31000",
                            formattedaddress:
                                "27 All. Forain-François Verdier, 31000 Toulouse, France",
                            placeid: "ChIJzf_Tzpq8rhIRcf_issvRnYc",
                            lng: 1.4516061,
                            lat: 43.5999787,
                        },
                        nationality: {
                            id: 1,
                            labelfr: "Française",
                            labelen: "French",
                            labelde: "Französisch",
                            code: "0",
                        },
                        firstname: "Jean",
                        lastname: "Dupont",
                        gender: "MALE",
                        phonenumber: "",
                        email: "worker@izipropal.com",
                        owner: 5,
                        documents: [
                            {
                                id: 1,
                                file: "/media/documents/2021-11/2020_CRUDETTES.pdf",
                                category: "CV",
                            },
                        ],
                    },
                    {
                        id: 2,
                        created: "2021-11-21T16:28:28.063296+00:00",
                        modified: "2021-11-21T16:28:28.063354+00:00",
                        address: {
                            streetnumber: "27",
                            route: "Allées Forain-François Verdier",
                            locality: "Toulouse",
                            administrativearealevel2: "Haute-Garonne",
                            administrativearealevel1: "Occitanie",
                            country: "FR",
                            postalcode: "31000",
                            formattedaddress:
                                "27 All. Forain-François Verdier, 31000 Toulouse, France",
                            placeid: "ChIJzf_Tzpq8rhIRcf_issvRnYc",
                            lng: 1.4516061,
                            lat: 43.5999787,
                        },
                        nationality: {
                            id: 1,
                            labelfr: "Française",
                            labelen: "French",
                            labelde: "Französisch",
                            code: "0",
                        },
                        firstname: "Jean",
                        lastname: "Dupont",
                        gender: "MALE",
                        phonenumber: "",
                        email: "worker@izipropal.com",
                        owner: 5,
                        documents: [
                            {
                                id: 1,
                                file: "/media/documents/2021-11/2020_CRUDETTES.pdf",
                                category: "CV",
                            },
                        ],
                    },
                ],
                documents: [
                    {
                        id: 2,
                        file: "/media/documents/2021-11/izi_orange.png",
                        category: "CV",
                    },
                ],
            },
            {
                id: 2,
                created: "2021-11-21T16:33:26.602614+00:00",
                modified: "2021-11-21T16:33:26.602713+00:00",
                status: "PUBLISHED",
                tender: 2,
                author: {
                    id: 5,
                    establishment: {
                        id: 1,
                        name: "The Central Bank",
                        siret: "5034394335673321",
                        address: {
                            streetnumber: "55",
                            route: "Chemin du Marais de Lenglet",
                            locality: "Toulouse",
                            administrativearealevel2: "Pas-de-Calais",
                            administrativearealevel1: "Hauts-de-France",
                            country: "FR",
                            postalcode: "62120",
                            formattedaddress:
                                "55 Chem. du Marais de Lenglet, 62120 Aire-sur-la-Lys, France",
                            placeid:
                                "Ejw1NSBDaGVtLiBkdSBNYXJhaXMgZGUgTGVuZ2xldCwgNjIxMjAgQWlyZS1zdXItbGEtTHlzLCBGcmFuY2UiGhIYChQKEgmTO_kYzALdRxEOzeYRehbVnRA3",
                            lng: 2.4193453,
                            lat: 50.6273972,
                        },
                    },
                    business_sectors: [
                        {
                            id: 10,
                            code: 10,
                            labelfr: "Banques",
                            labelen: "Banks",
                            labelde: "Banken",
                        },
                        {
                            id: 41,
                            code: 41,
                            labelfr: "Mode",
                            labelen: "Fashion",
                            labelde: "Mode / Fashion",
                        },
                        {
                            id: 38,
                            code: 38,
                            labelfr: "Télécommunications",
                            labelen: "Telecommunications",
                            labelde: "Telekommunikation",
                        },
                    ],
                },
                publishdate: "2021-11-21T16:17:36+00:00",
                message:
                    "Ceci est le message supplémentaire fourni par l'agence.\r\nIl peut être multiligne",
                coefficient0: 1.5,
                coefficient1: 2.3,
                includeterms: true,
                increasedcoefficient0: null,
                increasedcoefficient1: null,
                nbdays: null,
                nbhours: null,
                offer: true,
                otherexpenses0: null,
                otherexpenses1: null,
                prepaidoffer: true,
                rawhourlyrate: null,
                total0: 4500.0,
                total1: 2500.0,
                workers: [
                    {
                        id: 1,
                        created: "2021-11-21T16:28:28.063296+00:00",
                        modified: "2021-11-21T16:28:28.063354+00:00",
                        address: {
                            streetnumber: "27",
                            route: "Allées Forain-François Verdier",
                            locality: "Toulouse",
                            administrativearealevel2: "Haute-Garonne",
                            administrativearealevel1: "Occitanie",
                            country: "FR",
                            postalcode: "31000",
                            formattedaddress:
                                "27 All. Forain-François Verdier, 31000 Toulouse, France",
                            placeid: "ChIJzf_Tzpq8rhIRcf_issvRnYc",
                            lng: 1.4516061,
                            lat: 43.5999787,
                        },
                        nationality: {
                            id: 1,
                            labelfr: "Française",
                            labelen: "French",
                            labelde: "Französisch",
                            code: "0",
                        },
                        firstname: "Jean",
                        lastname: "Dupont",
                        gender: "MALE",
                        phonenumber: "",
                        email: "worker@izipropal.com",
                        owner: 5,
                        documents: [
                            {
                                id: 1,
                                file: "/media/documents/2021-11/2020_CRUDETTES.pdf",
                                category: "CV",
                            },
                        ],
                    },
                    {
                        id: 2,
                        created: "2021-11-21T16:28:28.063296+00:00",
                        modified: "2021-11-21T16:28:28.063354+00:00",
                        address: {
                            streetnumber: "27",
                            route: "Allées Forain-François Verdier",
                            locality: "Toulouse",
                            administrativearealevel2: "Haute-Garonne",
                            administrativearealevel1: "Occitanie",
                            country: "FR",
                            postalcode: "31000",
                            formattedaddress:
                                "27 All. Forain-François Verdier, 31000 Toulouse, France",
                            placeid: "ChIJzf_Tzpq8rhIRcf_issvRnYc",
                            lng: 1.4516061,
                            lat: 43.5999787,
                        },
                        nationality: {
                            id: 1,
                            labelfr: "Française",
                            labelen: "French",
                            labelde: "Französisch",
                            code: "0",
                        },
                        firstname: "Jean",
                        lastname: "Dupont",
                        gender: "MALE",
                        phonenumber: "",
                        email: "worker@izipropal.com",
                        owner: 5,
                        documents: [
                            {
                                id: 1,
                                file: "/media/documents/2021-11/2020_CRUDETTES.pdf",
                                category: "CV",
                            },
                        ],
                    },
                ],
                documents: [
                    {
                        id: 2,
                        file: "/media/documents/2021-11/izi_orange.png",
                        category: "CV",
                    },
                ],
            },
            {
                id: 3,
                created: "2021-11-21T16:33:26.602614+00:00",
                modified: "2021-11-21T16:33:26.602713+00:00",
                status: "PUBLISHED",
                tender: 2,
                author: {
                    id: 5,
                    establishment: {
                        id: 1,
                        name: "NaNLABS",
                        siret: "507639433777893",
                        address: {
                            streetnumber: "55",
                            route: "Chemin du Marais de Lenglet",
                            locality: "Paris",
                            administrativearealevel2: "Pas-de-Calais",
                            administrativearealevel1: "Hauts-de-France",
                            country: "FR",
                            postalcode: "62120",
                            formattedaddress:
                                "55 Chem. du Marais de Lenglet, 62120 Aire-sur-la-Lys, France",
                            placeid:
                                "Ejw1NSBDaGVtLiBkdSBNYXJhaXMgZGUgTGVuZ2xldCwgNjIxMjAgQWlyZS1zdXItbGEtTHlzLCBGcmFuY2UiGhIYChQKEgmTO_kYzALdRxEOzeYRehbVnRA3",
                            lng: 2.4193453,
                            lat: 50.6273972,
                        },
                    },
                    business_sectors: [
                        {
                            id: 10,
                            code: 10,
                            labelfr: "Banques",
                            labelen: "Banks",
                            labelde: "Banken",
                        },
                        {
                            id: 41,
                            code: 41,
                            labelfr: "Mode",
                            labelen: "Fashion",
                            labelde: "Mode / Fashion",
                        },
                        {
                            id: 38,
                            code: 38,
                            labelfr: "Télécommunications",
                            labelen: "Telecommunications",
                            labelde: "Telekommunikation",
                        },
                    ],
                },
                publishdate: "2021-11-21T16:17:36+00:00",
                message:
                    "Ceci est le message supplémentaire fourni par l'agence.\r\nIl peut être multiligne",
                coefficient0: 1.87,
                coefficient1: 1.65,
                includeterms: true,
                increasedcoefficient0: null,
                increasedcoefficient1: null,
                nbdays: null,
                nbhours: null,
                offer: true,
                otherexpenses0: null,
                otherexpenses1: null,
                prepaidoffer: true,
                rawhourlyrate: null,
                total0: 3500.0,
                total1: 1500.0,
                workers: [
                    {
                        id: 1,
                        created: "2021-11-21T16:28:28.063296+00:00",
                        modified: "2021-11-21T16:28:28.063354+00:00",
                        address: {
                            streetnumber: "27",
                            route: "Allées Forain-François Verdier",
                            locality: "Toulouse",
                            administrativearealevel2: "Haute-Garonne",
                            administrativearealevel1: "Occitanie",
                            country: "FR",
                            postalcode: "31000",
                            formattedaddress:
                                "27 All. Forain-François Verdier, 31000 Toulouse, France",
                            placeid: "ChIJzf_Tzpq8rhIRcf_issvRnYc",
                            lng: 1.4516061,
                            lat: 43.5999787,
                        },
                        nationality: {
                            id: 1,
                            labelfr: "Française",
                            labelen: "French",
                            labelde: "Französisch",
                            code: "0",
                        },
                        firstname: "Jean",
                        lastname: "Dupont",
                        gender: "MALE",
                        phonenumber: "",
                        email: "worker@izipropal.com",
                        owner: 5,
                        documents: [
                            {
                                id: 1,
                                file: "/media/documents/2021-11/2020_CRUDETTES.pdf",
                                category: "CV",
                            },
                        ],
                    },
                    {
                        id: 2,
                        created: "2021-11-21T16:28:28.063296+00:00",
                        modified: "2021-11-21T16:28:28.063354+00:00",
                        address: {
                            streetnumber: "27",
                            route: "Allées Forain-François Verdier",
                            locality: "Toulouse",
                            administrativearealevel2: "Haute-Garonne",
                            administrativearealevel1: "Occitanie",
                            country: "FR",
                            postalcode: "31000",
                            formattedaddress:
                                "27 All. Forain-François Verdier, 31000 Toulouse, France",
                            placeid: "ChIJzf_Tzpq8rhIRcf_issvRnYc",
                            lng: 1.4516061,
                            lat: 43.5999787,
                        },
                        nationality: {
                            id: 1,
                            labelfr: "Française",
                            labelen: "French",
                            labelde: "Französisch",
                            code: "0",
                        },
                        firstname: "Jean",
                        lastname: "Dupont",
                        gender: "MALE",
                        phonenumber: "",
                        email: "worker@izipropal.com",
                        owner: 5,
                        documents: [
                            {
                                id: 1,
                                file: "/media/documents/2021-11/2020_CRUDETTES.pdf",
                                category: "CV",
                            },
                        ],
                    },
                ],
                documents: [
                    {
                        id: 2,
                        file: "/media/documents/2021-11/izi_orange.png",
                        category: "CV",
                    },
                ],
            },
        ],
    },
    {
        id: 2,
        created: "2021-11-21T16:55:20.331884+00:00",
        modified: "2021-11-21T16:55:20.405746+00:00",
        status: "PUBLISHED",
        author: {
            id: 33,
            establishment: {
                id: 1,
                name: "MIRONOV PHILIPPE",
                siret: "50493943300014",
                address: {
                    streetnumber: "55",
                    route: "Chemin du Marais de Lenglet",
                    locality: "Lyonnais",
                    administrativearealevel2: "Pas-de-Calais",
                    administrativearealevel1: "Hauts-de-France",
                    country: "FR",
                    postalcode: "62120",
                    formattedaddress:
                        "55 Chem. du Marais de Lenglet, 62120 Aire-sur-la-Lys, France",
                    placeid:
                        "Ejw1NSBDaGVtLiBkdSBNYXJhaXMgZGUgTGVuZ2xldCwgNjIxMjAgQWlyZS1zdXItbGEtTHlzLCBGcmFuY2UiGhIYChQKEgmTO_kYzALdRxEOzeYRehbVnRA3",
                    lng: 2.4193453,
                    lat: 50.6273972,
                },
            },
            business_sectors: [],
        },
        tendertype: "MANAGED",
        clientref: "MonRef 54",
        jobtitle: "DevOps",
        remote: true,
        numberofworkers: 1,
        workertype: "PLACEMENT",
        contracttype: "CDD",
        start: "2021-12-10T00:00:00+00:00",
        end: "2022-09-15T23:59:59+00:00",
        hourscount: 2039.98,
        grosssalary: 70.0,
        salarycurrency: "EUR",
        recruitmentreason: "ACC_TEMP",
        requireddriverlicense: "",
        vehiclerequired: "NO",
        formation: "",
        certification: "",
        software: "",
        budget: null,
        budgetcurrency: null,
        payroll: 2,
        additionalpayrollinformation: "",
        firstname: "Rémy",
        lastname: "Bargas",
        phonenumber: "+336548645324",
        contactinformation: "This info is about me and our company, welcome",
        publishdate: "2021-11-21T16:49:00+00:00",
        workplace: {
            streetnumber: "55",
            route: "Chemin du Marais de Lenglet",
            locality: "Lyonnais",
            administrativearealevel2: "Pas-de-Calais",
            administrativearealevel1: "Hauts-de-France",
            country: "FR",
            postalcode: "62120",
            formattedaddress:
                "55 Chem. du Marais de Lenglet, 62120 Aire-sur-la-Lys, France",
            placeid:
                "Ejw1NSBDaGVtLiBkdSBNYXJhaXMgZGUgTGVuZ2xldCwgNjIxMjAgQWlyZS1zdXItbGEtTHlzLCBGcmFuY2UiGhIYChQKEgmTO_kYzALdRxEOzeYRehbVnRA3",
            lng: 2.4193453,
            lat: 50.6273972,
        },
        business_sectors: [
            {
                id: 4,
                code: 28,
                labelfr: "Informatique / Télécommunication",
                labelen: "Information Technologies",
                labelde: "Freizeit / Kultur / Sport",
            },
            {
                id: 5,
                code: 33,
                labelfr: "L'administration du système",
                labelen: "System Administration",
                labelde: "Personaldienstleistung",
            },
            {
                id: 6,
                code: 36,
                labelfr: "GNU/Linux",
                labelen: "GNU/Linux",
                labelde: "Dienstleistungen allgemein",
            },
            {
                id: 7,
                code: 36,
                labelfr: "Travail à distance",
                labelen: "Remote",
                labelde: "Dienstleistungen allgemein",
            },
            
        ],
        providedworkers: [
            {
                id: 2,
                created: "2021-11-21T16:48:12.859554+00:00",
                modified: "2021-11-21T16:48:12.859696+00:00",
                address: {
                    streetnumber: "118",
                    route: "Chemin des Basses Moulières",
                    locality: "Grasse",
                    administrativearealevel2: "Alpes-Maritimes",
                    administrativearealevel1: "Provence-Alpes-Côte d'Azur",
                    country: "FR",
                    postalcode: "06130",
                    formattedaddress:
                        "118 Chem. des Basses Moulières, 06130 Grasse, France",
                    placeid: "ChIJtZiQh50ozBIR0jzGgO0NJ1E",
                    lng: 6.9212006,
                    lat: 43.632528,
                },
                nationality: {
                    id: 1,
                    labelfr: "Française",
                    labelen: "French",
                    labelde: "Französisch",
                    code: "0",
                },
                firstname: "Roberto",
                lastname: "Legrand",
                gender: "MALE",
                phonenumber: "+33695478454",
                email: "roberto@izipropal.com",
                owner: 2,
                documents: [
                    {
                        id: 3,
                        file: "/media/documents/2021-11/forgotsomething.jpg",
                        category: "CV",
                    },
                ],
            },
            {
                id: 1,
                created: "2021-11-21T16:28:28.063296+00:00",
                modified: "2021-11-21T16:28:28.063354+00:00",
                address: {
                    streetnumber: "27",
                    route: "Allées Forain-François Verdier",
                    locality: "Toulouse",
                    administrativearealevel2: "Haute-Garonne",
                    administrativearealevel1: "Occitanie",
                    country: "FR",
                    postalcode: "31000",
                    formattedaddress:
                        "27 All. Forain-François Verdier, 31000 Toulouse, France",
                    placeid: "ChIJzf_Tzpq8rhIRcf_issvRnYc",
                    lng: 1.4516061,
                    lat: 43.5999787,
                },
                nationality: {
                    id: 1,
                    labelfr: "Française",
                    labelen: "French",
                    labelde: "Französisch",
                    code: "0",
                },
                firstname: "Jean",
                lastname: "Dupont",
                gender: "MALE",
                phonenumber: "",
                email: "worker@izipropal.com",
                owner: 5,
                documents: [
                    {
                        id: 1,
                        file: "/media/documents/2021-11/2020_CRUDETTES.pdf",
                        category: "CV",
                    },
                ],
            },
            {
                id: 3,
                created: "2021-11-21T16:48:12.859554+00:00",
                modified: "2021-11-21T16:48:12.859696+00:00",
                address: {
                    streetnumber: "118",
                    route: "Chemin des Basses Moulières",
                    locality: "Grasse",
                    administrativearealevel2: "Alpes-Maritimes",
                    administrativearealevel1: "Provence-Alpes-Côte d'Azur",
                    country: "FR",
                    postalcode: "06130",
                    formattedaddress:
                        "118 Chem. des Basses Moulières, 06130 Grasse, France",
                    placeid: "ChIJtZiQh50ozBIR0jzGgO0NJ1E",
                    lng: 6.9212006,
                    lat: 43.632528,
                },
                nationality: {
                    id: 1,
                    labelfr: "Française",
                    labelen: "French",
                    labelde: "Französisch",
                    code: "0",
                },
                firstname: "Thomas",
                lastname: "Lavigne",
                gender: "MALE",
                phonenumber: "+33695453299",
                email: "thomas@izipropal.com",
                owner: 2,
                documents: [
                    {
                        id: 3,
                        file: "/media/documents/2021-11/forgotsomething.jpg",
                        category: "CV",
                    },
                ],
            },
            
        ],
        periods: [
            {
                id: 2,
                tender: 3,
                start: "2021-12-21T00:00:00+00:00",
                end: "2022-03-15T23:59:59+00:00",
                pause: 30,
            },
        ],
        requiredlanguages: [],
        proposals: [
            {
                id: 4,
                created: "2021-11-21T16:33:26.602614+00:00",
                modified: "2021-11-21T16:33:26.602713+00:00",
                status: "PUBLISHED",
                tender: 2,
                author: {
                    id: 5,
                    establishment: {
                        id: 1,
                        name: "Terasol Technologies",
                        siret: "50763943300014",
                        address: {
                            streetnumber: "55",
                            route: "Chemin du Marais de Lenglet",
                            locality: "Toulouse",
                            administrativearealevel2: "Pas-de-Calais",
                            administrativearealevel1: "Hauts-de-France",
                            country: "FR",
                            postalcode: "62120",
                            formattedaddress:
                                "55 Chem. du Marais de Lenglet, 62120 Aire-sur-la-Lys, France",
                            placeid:
                                "Ejw1NSBDaGVtLiBkdSBNYXJhaXMgZGUgTGVuZ2xldCwgNjIxMjAgQWlyZS1zdXItbGEtTHlzLCBGcmFuY2UiGhIYChQKEgmTO_kYzALdRxEOzeYRehbVnRA3",
                            lng: 2.4193453,
                            lat: 50.6273972,
                        },
                    },
                    business_sectors: [
                        {
                            id: 10,
                            code: 10,
                            labelfr: "Banques",
                            labelen: "Banks",
                            labelde: "Banken",
                        },
                        {
                            id: 41,
                            code: 41,
                            labelfr: "Mode",
                            labelen: "Fashion",
                            labelde: "Mode / Fashion",
                        },
                        {
                            id: 38,
                            code: 38,
                            labelfr: "Télécommunications",
                            labelen: "Telecommunications",
                            labelde: "Telekommunikation",
                        },
                    ],
                },
                publishdate: "2021-11-21T16:17:36+00:00",
                message:
                    "Ceci est le message supplémentaire fourni par l'agence.\r\nIl peut être multiligne",
                coefficient0: 2.4,
                coefficient1: 2.65,
                includeterms: true,
                increasedcoefficient0: null,
                increasedcoefficient1: null,
                nbdays: null,
                nbhours: null,
                offer: true,
                otherexpenses0: null,
                otherexpenses1: null,
                prepaidoffer: true,
                rawhourlyrate: null,
                total0: 4100.0,
                total1: 1950.0,
                workers: [
                    {
                        id: 1,
                        created: "2021-11-21T16:28:28.063296+00:00",
                        modified: "2021-11-21T16:28:28.063354+00:00",
                        address: {
                            streetnumber: "27",
                            route: "Allées Forain-François Verdier",
                            locality: "Toulouse",
                            administrativearealevel2: "Haute-Garonne",
                            administrativearealevel1: "Occitanie",
                            country: "FR",
                            postalcode: "31000",
                            formattedaddress:
                                "27 All. Forain-François Verdier, 31000 Toulouse, France",
                            placeid: "ChIJzf_Tzpq8rhIRcf_issvRnYc",
                            lng: 1.4516061,
                            lat: 43.5999787,
                        },
                        nationality: {
                            id: 1,
                            labelfr: "Française",
                            labelen: "French",
                            labelde: "Französisch",
                            code: "0",
                        },
                        firstname: "Jean",
                        lastname: "Dupont",
                        gender: "MALE",
                        phonenumber: "",
                        email: "worker@izipropal.com",
                        owner: 5,
                        documents: [
                            {
                                id: 1,
                                file: "/media/documents/2021-11/2020_CRUDETTES.pdf",
                                category: "CV",
                            },
                        ],
                    },
                ],
                documents: [
                    {
                        id: 2,
                        file: "/media/documents/2021-11/izi_orange.png",
                        category: "CV",
                    },
                ],
            },
            {
                id: 5,
                created: "2021-11-21T16:33:26.602614+00:00",
                modified: "2021-11-21T16:33:26.602713+00:00",
                status: "PUBLISHED",
                tender: 2,
                author: {
                    id: 5,
                    establishment: {
                        id: 1,
                        name: "Unicorn Company",
                        siret: "50903943355534",
                        address: {
                            streetnumber: "55",
                            route: "Chemin du Marais de Lenglet",
                            locality: "Marseille",
                            administrativearealevel2: "Pas-de-Calais",
                            administrativearealevel1: "Hauts-de-France",
                            country: "FR",
                            postalcode: "62120",
                            formattedaddress:
                                "55 Chem. du Marais de Lenglet, 62120 Aire-sur-la-Lys, France",
                            placeid:
                                "Ejw1NSBDaGVtLiBkdSBNYXJhaXMgZGUgTGVuZ2xldCwgNjIxMjAgQWlyZS1zdXItbGEtTHlzLCBGcmFuY2UiGhIYChQKEgmTO_kYzALdRxEOzeYRehbVnRA3",
                            lng: 2.4193453,
                            lat: 50.6273972,
                        },
                    },
                    business_sectors: [
                        {
                            id: 10,
                            code: 10,
                            labelfr: "Banques",
                            labelen: "Banks",
                            labelde: "Banken",
                        },
                        {
                            id: 41,
                            code: 41,
                            labelfr: "Mode",
                            labelen: "Fashion",
                            labelde: "Mode / Fashion",
                        },
                        {
                            id: 38,
                            code: 38,
                            labelfr: "Télécommunications",
                            labelen: "Telecommunications",
                            labelde: "Telekommunikation",
                        },
                    ],
                },
                publishdate: "2021-11-21T16:17:36+00:00",
                message:
                    "Ceci est le message supplémentaire fourni par l'agence.\r\nIl peut être multiligne",
                coefficient0: 1.62,
                coefficient1: 1.88,
                includeterms: true,
                increasedcoefficient0: null,
                increasedcoefficient1: null,
                nbdays: null,
                nbhours: null,
                offer: true,
                otherexpenses0: null,
                otherexpenses1: null,
                prepaidoffer: true,
                rawhourlyrate: null,
                total0: 4000.0,
                total1: 1800.0,
                workers: [
                    {
                        id: 1,
                        created: "2021-11-21T16:28:28.063296+00:00",
                        modified: "2021-11-21T16:28:28.063354+00:00",
                        address: {
                            streetnumber: "27",
                            route: "Allées Forain-François Verdier",
                            locality: "Toulouse",
                            administrativearealevel2: "Haute-Garonne",
                            administrativearealevel1: "Occitanie",
                            country: "FR",
                            postalcode: "31000",
                            formattedaddress:
                                "27 All. Forain-François Verdier, 31000 Toulouse, France",
                            placeid: "ChIJzf_Tzpq8rhIRcf_issvRnYc",
                            lng: 1.4516061,
                            lat: 43.5999787,
                        },
                        nationality: {
                            id: 1,
                            labelfr: "Française",
                            labelen: "French",
                            labelde: "Französisch",
                            code: "0",
                        },
                        firstname: "Jean",
                        lastname: "Dupont",
                        gender: "MALE",
                        phonenumber: "",
                        email: "worker@izipropal.com",
                        owner: 5,
                        documents: [
                            {
                                id: 1,
                                file: "/media/documents/2021-11/2020_CRUDETTES.pdf",
                                category: "CV",
                            },
                        ],
                    },
                ],
                documents: [
                    {
                        id: 2,
                        file: "/media/documents/2021-11/izi_orange.png",
                        category: "CV",
                    },
                ],
            },
        ],
    },
    {
        id: 3,
        created: "2021-11-21T16:55:20.331884+00:00",
        modified: "2021-11-22T16:55:20.405746+00:00",
        status: "PUBLISHED",
        author: {
            id: 33,
            establishment: {
                id: 1,
                name: "MIRONOV PHILIPPE",
                siret: "50763943300014",
                address: {
                    streetnumber: "55",
                    route: "Chemin du Marais de Lenglet",
                    locality: "Marseille",
                    administrativearealevel2: "Pas-de-Calais",
                    administrativearealevel1: "Hauts-de-France",
                    country: "FR",
                    postalcode: "62120",
                    formattedaddress:
                        "55 Chem. du Marais de Lenglet, 62120 Aire-sur-la-Lys, France",
                    placeid:
                        "Ejw1NSBDaGVtLiBkdSBNYXJhaXMgZGUgTGVuZ2xldCwgNjIxMjAgQWlyZS1zdXItbGEtTHlzLCBGcmFuY2UiGhIYChQKEgmTO_kYzALdRxEOzeYRehbVnRA3",
                    lng: 2.4193453,
                    lat: 50.6273972,
                },
            },
            business_sectors: [],
        },
        tendertype: "MANAGED",
        clientref: "MonAutreRef 69 F/H",
        jobtitle: "Senior Recruiter",
        remote: false,
        numberofworkers: 2,
        workertype: "PLACEMENT",
        contracttype: "CDI",
        start: "2021-11-15T00:00:00+00:00",
        end: "2022-12-15T23:59:59+00:00",
        hourscount: 2039.98,
        grosssalary: 65.0,
        salarycurrency: "EUR",
        recruitmentreason: "ACC_TEMP",
        requireddriverlicense: "",
        vehiclerequired: "NO",
        formation: "",
        certification: "",
        software: "",
        budget: null,
        budgetcurrency: null,
        payroll: 2,
        additionalpayrollinformation: "",
        firstname: "Pavel",
        lastname: "Durov",
        phonenumber: "+336544534588",
        contactinformation: "",
        publishdate: "2021-11-21T16:49:00+00:00",
        workplace: {
            streetnumber: "55",
            route: "Chemin du Marais de Lenglet",
            locality: "Toulouse",
            administrativearealevel2: "Pas-de-Calais",
            administrativearealevel1: "Hauts-de-France",
            country: "FR",
            postalcode: "62120",
            formattedaddress:
                "55 Chem. du Marais de Lenglet, 62120 Aire-sur-la-Lys, France",
            placeid:
                "Ejw1NSBDaGVtLiBkdSBNYXJhaXMgZGUgTGVuZ2xldCwgNjIxMjAgQWlyZS1zdXItbGEtTHlzLCBGcmFuY2UiGhIYChQKEgmTO_kYzALdRxEOzeYRehbVnRA3",
            lng: 2.4193453,
            lat: 50.6273972,
        },
        business_sectors: [
            {
                id: 8,
                code: 33,
                labelfr: "Ressources humaines",
                labelen: "Human resources",
                labelde: "Personaldienstleistung",
            },
            {
                id: 9,
                code: 33,
                labelfr: "Informatique / Télécommunication",
                labelen: "Information Technologies",
                labelde: "Personaldienstleistung",
            },
        ],
        providedworkers: [
            {
                id: 2,
                created: "2021-11-21T16:48:12.859554+00:00",
                modified: "2021-11-21T16:48:12.859696+00:00",
                address: {
                    streetnumber: "118",
                    route: "Chemin des Basses Moulières",
                    locality: "Grasse",
                    administrativearealevel2: "Alpes-Maritimes",
                    administrativearealevel1: "Provence-Alpes-Côte d'Azur",
                    country: "FR",
                    postalcode: "06130",
                    formattedaddress:
                        "118 Chem. des Basses Moulières, 06130 Grasse, France",
                    placeid: "ChIJtZiQh50ozBIR0jzGgO0NJ1E",
                    lng: 6.9212006,
                    lat: 43.632528,
                },
                nationality: {
                    id: 1,
                    labelfr: "Française",
                    labelen: "French",
                    labelde: "Französisch",
                    code: "0",
                },
                firstname: "Roberto",
                lastname: "Legrand",
                gender: "MALE",
                phonenumber: "+33695478454",
                email: "roberto@izipropal.com",
                owner: 2,
                documents: [
                    {
                        id: 3,
                        file: "/media/documents/2021-11/forgotsomething.jpg",
                        category: "CV",
                    },
                ],
            },
        ],
        periods: [
            {
                id: 2,
                tender: 3,
                start: "2021-12-21T00:00:00+00:00",
                end: "2022-03-15T23:59:59+00:00",
                pause: 30,
            },
        ],
        requiredlanguages: [],
        proposals: [],
    },
    {
        id: 4,
        created: "2021-11-21T16:55:20.331884+00:00",
        modified: "2021-11-22T16:55:20.405746+00:00",
        status: "PUBLISHED",
        author: {
            id: 33,
            establishment: {
                id: 1,
                name: "MIRONOV PHILIPPE",
                siret: "50763943300014",
                address: {
                    streetnumber: "55",
                    route: "Chemin du Marais de Lenglet",
                    locality: "Aire-sur-la-Lys",
                    administrativearealevel2: "Pas-de-Calais",
                    administrativearealevel1: "Hauts-de-France",
                    country: "FR",
                    postalcode: "62120",
                    formattedaddress:
                        "55 Chem. du Marais de Lenglet, 62120 Aire-sur-la-Lys, France",
                    placeid:
                        "Ejw1NSBDaGVtLiBkdSBNYXJhaXMgZGUgTGVuZ2xldCwgNjIxMjAgQWlyZS1zdXItbGEtTHlzLCBGcmFuY2UiGhIYChQKEgmTO_kYzALdRxEOzeYRehbVnRA3",
                    lng: 2.4193453,
                    lat: 50.6273972,
                },
            },
            business_sectors: [],
        },
        tendertype: "DELEGATION",
        clientref: "AutreRef 72",
        jobtitle: "QA Engineer",
        remote: false,
        numberofworkers: 1,
        workertype: "PLACEMENT",
        contracttype: "CDD",
        start: "2021-12-21T00:00:00+00:00",
        end: "2022-05-15T23:59:59+00:00",
        hourscount: 2039.98,
        grosssalary: 55.0,
        salarycurrency: "EUR",
        recruitmentreason: "ACC_TEMP",
        requireddriverlicense: "",
        vehiclerequired: "NO",
        formation: "",
        certification: "",
        software: "",
        budget: null,
        budgetcurrency: null,
        payroll: 2,
        additionalpayrollinformation: "",
        firstname: "Elon",
        lastname: "Musk",
        phonenumber: "+3365486456456",
        contactinformation: "",
        publishdate: "2021-11-21T16:49:00+00:00",
        workplace: {
            streetnumber: "55",
            route: "Chemin du Marais de Lenglet",
            locality: "Grasse",
            administrativearealevel2: "Pas-de-Calais",
            administrativearealevel1: "Hauts-de-France",
            country: "FR",
            postalcode: "62120",
            formattedaddress:
                "55 Chem. du Marais de Lenglet, 62120 Aire-sur-la-Lys, France",
            placeid:
                "Ejw1NSBDaGVtLiBkdSBNYXJhaXMgZGUgTGVuZ2xldCwgNjIxMjAgQWlyZS1zdXItbGEtTHlzLCBGcmFuY2UiGhIYChQKEgmTO_kYzALdRxEOzeYRehbVnRA3",
            lng: 2.4193453,
            lat: 50.6273972,
        },
        business_sectors: [
            {
                id: 10,
                code: 28,
                labelfr: "Informatique / Télécommunication",
                labelen: "Information Technologies",
                labelde: "Freizeit / Kultur / Sport",
            },
            {
                id: 11,
                code: 33,
                labelfr: "Mobile",
                labelen: "Mobile",
                labelde: "Personaldienstleistung",
            },
            {
                id: 12,
                code: 36,
                labelfr: "Automatisation de l'assurance qualité",
                labelen: "QA Automation",
                labelde: "Dienstleistungen allgemein",
            },
        ],
        providedworkers: [
            {
                id: 2,
                created: "2021-11-21T16:48:12.859554+00:00",
                modified: "2021-11-21T16:48:12.859696+00:00",
                address: {
                    streetnumber: "118",
                    route: "Chemin des Basses Moulières",
                    locality: "Grasse",
                    administrativearealevel2: "Alpes-Maritimes",
                    administrativearealevel1: "Provence-Alpes-Côte d'Azur",
                    country: "FR",
                    postalcode: "06130",
                    formattedaddress:
                        "118 Chem. des Basses Moulières, 06130 Grasse, France",
                    placeid: "ChIJtZiQh50ozBIR0jzGgO0NJ1E",
                    lng: 6.9212006,
                    lat: 43.632528,
                },
                nationality: {
                    id: 1,
                    labelfr: "Française",
                    labelen: "French",
                    labelde: "Französisch",
                    code: "0",
                },
                firstname: "Roberto",
                lastname: "Legrand",
                gender: "MALE",
                phonenumber: "+33695478454",
                email: "roberto@izipropal.com",
                owner: 2,
                documents: [
                    {
                        id: 3,
                        file: "/media/documents/2021-11/forgotsomething.jpg",
                        category: "CV",
                    },
                ],
            },
        ],
        periods: [
            {
                id: 2,
                tender: 3,
                start: "2021-12-21T00:00:00+00:00",
                end: "2022-03-15T23:59:59+00:00",
                pause: 30,
            },
        ],
        requiredlanguages: [],
        proposals: [],
    },
    {
        id: 5,
        created: "2021-11-21T16:55:20.331884+00:00",
        modified: "2021-11-22T16:55:20.405746+00:00",
        status: "PUBLISHED",
        author: {
            id: 33,
            establishment: {
                id: 1,
                name: "MIRONOV PHILIPPE",
                siret: "50763943300014",
                address: {
                    streetnumber: "55",
                    route: "Chemin du Marais de Lenglet",
                    locality: "Aire-sur-la-Lys",
                    administrativearealevel2: "Pas-de-Calais",
                    administrativearealevel1: "Hauts-de-France",
                    country: "FR",
                    postalcode: "62120",
                    formattedaddress:
                        "55 Chem. du Marais de Lenglet, 62120 Aire-sur-la-Lys, France",
                    placeid:
                        "Ejw1NSBDaGVtLiBkdSBNYXJhaXMgZGUgTGVuZ2xldCwgNjIxMjAgQWlyZS1zdXItbGEtTHlzLCBGcmFuY2UiGhIYChQKEgmTO_kYzALdRxEOzeYRehbVnRA3",
                    lng: 2.4193453,
                    lat: 50.6273972,
                },
            },
            business_sectors: [],
        },
        tendertype: "MANAGED",
        clientref: "MonAutreRef 90 F/H",
        jobtitle: "Backend Developer",
        remote: false,
        numberofworkers: 1,
        workertype: "PLACEMENT",
        contracttype: "CDD",
        start: "2021-12-21T00:00:00+00:00",
        end: "2022-06-15T23:59:59+00:00",
        hourscount: 2039.98,
        grosssalary: 75.0,
        salarycurrency: "EUR",
        recruitmentreason: "ACC_TEMP",
        requireddriverlicense: "",
        vehiclerequired: "NO",
        formation: "",
        certification: "",
        software: "JVM, AWS, Linux",
        budget: null,
        budgetcurrency: null,
        payroll: 2,
        additionalpayrollinformation: "",
        firstname: "Rémy",
        lastname: "Bargas",
        phonenumber: "+336548645324",
        contactinformation: "",
        publishdate: "2021-11-21T16:49:00+00:00",
        workplace: {
            streetnumber: "55",
            route: "Chemin du Marais de Lenglet",
            locality: "Aire-sur-la-Lys",
            administrativearealevel2: "Pas-de-Calais",
            administrativearealevel1: "Hauts-de-France",
            country: "FR",
            postalcode: "62120",
            formattedaddress:
                "55 Chem. du Marais de Lenglet, 62120 Aire-sur-la-Lys, France",
            placeid:
                "Ejw1NSBDaGVtLiBkdSBNYXJhaXMgZGUgTGVuZ2xldCwgNjIxMjAgQWlyZS1zdXItbGEtTHlzLCBGcmFuY2UiGhIYChQKEgmTO_kYzALdRxEOzeYRehbVnRA3",
            lng: 2.4193453,
            lat: 50.6273972,
        },
        business_sectors: [
            {
                id: 13,
                code: 28,
                labelfr: "Informatique / Télécommunication",
                labelen: "Information Technologies",
                labelde: "Freizeit / Kultur / Sport",
            },
            {
                id: 14,
                code: 33,
                labelfr: "Bases de données",
                labelen: "Databases",
                labelde: "Personaldienstleistung",
            },
            {
                id: 15,
                code: 33,
                labelfr: "Java Core / Spring Boot",
                labelen: "Java Core / Spring Boot",
                labelde: "Personaldienstleistung",
            },
        ],
        providedworkers: [
            {
                id: 2,
                created: "2021-11-21T16:48:12.859554+00:00",
                modified: "2021-11-21T16:48:12.859696+00:00",
                address: {
                    streetnumber: "118",
                    route: "Chemin des Basses Moulières",
                    locality: "Grasse",
                    administrativearealevel2: "Alpes-Maritimes",
                    administrativearealevel1: "Provence-Alpes-Côte d'Azur",
                    country: "FR",
                    postalcode: "06130",
                    formattedaddress:
                        "118 Chem. des Basses Moulières, 06130 Grasse, France",
                    placeid: "ChIJtZiQh50ozBIR0jzGgO0NJ1E",
                    lng: 6.9212006,
                    lat: 43.632528,
                },
                nationality: {
                    id: 1,
                    labelfr: "Française",
                    labelen: "French",
                    labelde: "Französisch",
                    code: "0",
                },
                firstname: "Roberto",
                lastname: "Legrand",
                gender: "MALE",
                phonenumber: "+33695478454",
                email: "roberto@izipropal.com",
                owner: 2,
                documents: [
                    {
                        id: 3,
                        file: "/media/documents/2021-11/forgotsomething.jpg",
                        category: "CV",
                    },
                ],
            },
        ],
        periods: [
            {
                id: 2,
                tender: 3,
                start: "2021-12-21T00:00:00+00:00",
                end: "2022-03-15T23:59:59+00:00",
                pause: 30,
            },
        ],
        requiredlanguages: [],
        proposals: [],
    },
];
